name: 'Change permission'
description: 'Greet someone'
inputs:
  folder:  # id of input
    description: 'Change permission'
    required: true
    default: 'World'
runs:
  using: "composite"
  steps:
    - run: pwd
      shell: bash
    - run: ls -al
      shell: bash
    - run: chmod Hello ${{ inputs.folder }}.
      shell: bash